# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'smartnative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for smartnative
pod 'Kingfisher' 
pod 'SideMenu'
pod 'SDK-iOS', :git =>  "https://github.com/cloudpayments/SDK-iOS", :branch => "master"


end
